### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Mush-r00m** [2MinhetNguyles/Chaturbate-Recorder-GUI#1]
Would it be possible to not have a CMD window pop up everytime a model has begun to be recorder?
It can get in the way when doing other things & having to minimize every new window that pops up.
Thankyou for the Tool, its pretty much what i have been looking for :)

**Comment by 2MinhetNguyles** [comment]
The command window is actually FFMpeg, I will look into this when I get some free time to update this to the next version.

**Comment by 2MinhetNguyles** [comment]
I really don't know what causes the stuttering, I only really seem to get it when my internet is slow.... as it is a ffmpeg issue I can't really do anything about this, as this is only a front end.

I have taken you earlier request into account and it has been implemented in the newest version which I have upgraded from .HTA/VBscript to a compiled .EXE written in VB6.0. There are also extra features I have added as VB6.0 is far far far far easier to work with. Enjoy.
