### ISSUE TITLE
Null/Blank Model Name and Get Stream Address Key Press

### ISSUE THREAD

**Issue by clayinjax** [2MinhetNguyles/Chaturbate-Recorder-GUI#2]
I realize this is a minor issue, but if other steams are already running they terminate when the run time error "the parameter is incorrect" is triggered if a user presses "Get Steam Address" and they forgot to key input into "Please enter the model URL Below." It needs a null or blank test that runs the error message box already used for other input errors. Thanks for this project.

**Comment by 2MinhetNguyles** [comment]
Thanks for the report.

Yeah I probably should have put an error handler in for that, all done.
I have also fixed getting the correct stream URL since the recent update to the website.

**Comment by clayinjax** [comment]
I appreciate the note, thank you.
